# Generated by Django 4.1 on 2022-08-05 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_cal_app', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calendars',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
