# Generated by Django 4.1 on 2022-08-05 12:02

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main_cal_app', '0007_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='event id')),
                ('event_name', models.CharField(max_length=150, verbose_name='event name')),
                ('event_datetime', models.DateTimeField(default=datetime.datetime(2022, 8, 5, 12, 2, 59, 782010, tzinfo=datetime.timezone.utc), verbose_name='event datetime')),
                ('event_last_modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('event_desc', models.TextField(verbose_name='event description')),
                ('event_duration', models.DateTimeField(verbose_name='event duration')),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True),
        ),
    ]
