# Generated by Django 4.1 on 2022-08-05 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_cal_app', '0008_events_alter_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 5, 12, 13, 36, 605052, tzinfo=datetime.timezone.utc), verbose_name='event datetime'),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_duration',
            field=models.CharField(choices=[('30', '30 minutes'), ('1', '1 hour'), ('2', '2 hours'), ('4', '4 hours'), ('6', '6 hours'), ('12', '12hours'), ('1', '1 day'), ('2', '2 days'), ('3', '3 days')], default='1 hour', max_length=100, verbose_name='event duration'),
        ),
    ]
