# Generated by Django 4.1 on 2022-08-05 12:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_cal_app', '0009_alter_events_event_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendars',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_cal_app.users'),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 5, 12, 18, 47, 581488, tzinfo=datetime.timezone.utc), verbose_name='event datetime'),
        ),
    ]
