# Generated by Django 4.1 on 2022-08-05 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_cal_app', '0010_alter_calendars_email_alter_events_event_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='event_datetime',
        ),
        migrations.AddField(
            model_name='events',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 5, 12, 45, 56, 201365, tzinfo=datetime.timezone.utc), verbose_name='event date'),
        ),
        migrations.AddField(
            model_name='events',
            name='event_time',
            field=models.TimeField(default=datetime.datetime(2022, 8, 5, 12, 45, 56, 201505, tzinfo=datetime.timezone.utc), verbose_name='event date'),
        ),
    ]
